all : pool fetcher extractor
	
pool :
	rm -rf ../bin/pool/
	mkdir -p ../bin/pool/
	cp ./pool_client.js ./pool.js ../bin/pool/	

fetcher :
	rm -rf ../bin/pool/
	mkdir -p ../bin/pool/
	cp ./pool_client.js ./pool.js ../bin/pool/	

extractor :

